### ISSUE TITLE
PrivateKeyDer from other source?

### ISSUE THREAD

**Issue by VassilisM** [rustls/pki-types#36]
Hello. Not really an issue, rather a question.

Is there a possibility to create a PrivateKeyDer from a pem file?
Or a pfx file which contains both certificate and private key? Or from their already read bytes?

Better yet from an NcryptKey handle reading the certificate context and private key from windows store?

The thing is "bind_rustls_0_22" of actix-web is expecting a PrivateKeyDer which I am unable to provide. CertificateDer is ok; CertContext.to_der() is working, I hope. But the private key is a pain.

(CertContext and NcryptKey from schannel-rs)

Thank you.
PS: I know already that it is not supposed to be stored and extracted, but I maybe it is better than having both files laying around with the application files and is a customer requirement as well...

**Comment by cpu** [comment]
> Is there a possibility to create a PrivateKeyDer from a pem file?

Yes, take a look at [rustls-pemfile](https://docs.rs/rustls-pemfile/latest/rustls_pemfile/)

> Or a pfx file which contains both certificate and private key? 

There's no support for PFX in the Rustls ecosystem. You'd need to use an external crate and find a way to extract compatible DER for Rustls.

> Better yet from an NcryptKey handle reading the certificate context and private key from windows store?

Perhaps [rustls-cng](https://github.com/rustls/rustls-cng) would be helpful to you? I'm not familiar with the Windows APIs to know more than that rustls-cng exists.

**Comment by VassilisM** [comment]
Thank you for these. I have some new leads to follow now.
