### ISSUE TITLE
invalid authority or bad dns_name error when using IPv6 abbr

### ISSUE THREAD

**Issue by mokeyish** [rustls/pki-types#62]
Send DNS request to `https://[2001:4860:4860::8888]/dns-query` using H3

| IP | Host | Status |
| -- | -- | -- |
| 2001:4860:4860::8888 | `2001:4860:4860::8888` |  invalid authority |
| 2001:4860:4860::8888 | `[2001:4860:4860::8888]` |  bad dns_name |
| 2001:4860:4860::8888 | `2001:4860:4860:0000:0000:0000:0000:8888` | invalid authority |
| 2001:4860:4860::8888 | `dns.google` | success |

See also https://github.com/quinn-rs/quinn/issues/2005

For pki-types, I think we should keep the original string representation of IP?

https://github.com/rustls/pki-types/blob/9a1da55aab69064dc9fe566993d91e71187e6278/src/server_name.rs#L55

**Comment by mokeyish** [comment]
For pki-types, I think we should keep the original string representation of IP?

https://github.com/rustls/pki-types/blob/9a1da55aab69064dc9fe566993d91e71187e6278/src/server_name.rs#L55

**Comment by mokeyish** [comment]
> @mokeyish Can you share a more complete reproduction with just `pki-types`?

reproduce code:
```rs

ServerName::try_from("2001:4860:4860::8888").unwarp();

ServerName::try_from("[2001:4860:4860::8888]").unwarp();

```

**Comment by ctz** [comment]
Yes, the server name needs to be a valid IPv6 address, not a URL-wrapped one. You will need a URL parsing library to extract that. 

eg, if you were using the "url" crate, it is https://docs.rs/url/latest/url/struct.Url.html#method.host_str

**Comment by cpu** [comment]
> ServerName::try_from("2001:4860:4860::8888").unwrap();

This works fine with tip of `pki_types`.

> ServerName::try_from("[2001:4860:4860::8888]").unwarp();

As @ctz mentioned, this isn't a valid IPv6 address so it is expected to error.

**Comment by ctz** [comment]
Here's an example of parsing URLs using the `url` crate: 

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e11d11a5cc86c9f208cc3bcbe09ab785

**Comment by mokeyish** [comment]
> > ServerName::try_from("2001:4860:4860::8888").unwrap();
> Both work fine with tip of `pki_types`.

@cpu I tested it again and it was indeed parsed fine. It reports invalid authority error.

**Comment by cpu** [comment]
> It reports invalid authority error.

What "it" do you mean here, can you be more specific? None of the valid IPv6 addresses you shared produce any error from `pki_types`. I also don't think we have any code in Rustls, webpki or pki-types that emits an "invalid authority" error :thinking: 

> I'm not sure whether this should be supported

Nothing in Rustls operates with URLs so I don't think it's appropriate to support IPv6 URLs. IMO this should be handled at a higher layer. E.g. using the `url` crate (or another solution) to extract the IPv6 to then use with Rustls/pki-types instead of the URL.

**Comment by mokeyish** [comment]
@cpu These errors are reported at `quinn`, `it` means `quinn`. But regarding the verification of tls, quinn uses `pki-types` and `rustls`.

Here is the program and configuration to actually reproduce:

1. Download program https://github.com/mokeyish/smartdns-rs/releases/tag/v0.8.8-alpha.1

2. `./smartdns.conf`
  
    ```conf
    
    bind :8053
    cache-size 0
    
    # server-h3 2001:4860:4860::8888
    # server-h3 2001:4860:4860::8888 -host-name dns.google
    server-h3 2001:4860:4860::8888 -host-name 2001:4860:4860::8888
    # server https://[2001:4860:4860::8888]/dns-query#h3 -host-name dns.google
    # server https://[2001:4860:4860::8888]/dns-query -host-name 2001:4860:4860::8888
    
    ```
3. run

   ```sh
   smartdns run -c ./smartdns.conf -vvv

4. query DNS

   ```sh
   dig @127.0.0.1 -p 8053 google.com
   ```

5. error:

   ![image](https://github.com/user-attachments/assets/2caeb108-7622-47f0-951c-20fa6fda7067)

**Comment by cpu** [comment]
> These errors are reported at quinn

Understood. I think there's no indication there's a bug anywhere in Rustls. Further debugging should probably be done in a Quinn issue. 

Thanks!

**Comment by mokeyish** [comment]
I found that this problem occurs not only in HTTP/3 (Quinn), but also in HTTP/2. So it may not be Quinn's problem, but rustls's?

**Comment by cpu** [comment]
> I found that this problem occurs not only in HTTP/3 (Quinn), but also in HTTP/2. So it may not be Quinn's problem, but rustls's?

Rustls doesn't implement http/2. If you think you found a bug in Rustls the best idea is to open an issue on the main rustls repo demonstrating the bug _without_ any external code. e.g. by using one of the examples in the repo, or with a minimal reproducer of some sort

**Comment by mokeyish** [comment]
I know this, HTTP/2 and HTTP/3 both use TLS, which is Rustls. I need to further confirm which problem it is.

**Comment by mokeyish** [comment]
@ctz Thank you, this should not be the main problem. In fact, `tls_dns_name` can be specified directly. Look at the `smartdns.conf` above, there is a `-host-name` option.


There was indeed a problem with the parsing of the url, but I fixed it directly. The code is here, and there is also a unit test at the bottom.

https://github.com/mokeyish/smartdns-rs/blob/main/src/dns_url.rs
