### ISSUE TITLE
How about derive Eq for Cert/PrivateKey ？

### ISSUE THREAD

**Issue by zh-jq-b** [rustls/pki-types#9]
And should Der::Owned and Der::Borrowed to be considered PartialEq if they contains the same binary data?

**Comment by djc** [comment]
Seems okay to derive `Eq` for things that already derive `PartialEq`. Why do you need it? I don't know whether it would be good to implement `PartialEq` for `Der` directly... what's your use case?

**Comment by zh-jq-b** [comment]
For Eq, we need to check if the config (including the cert and the private key) has changed.
It is strange if Der::Owned is not equal to Der::Borrowed for the same key when we compare Vec<u8>.into() vs &[u8].into().

**Comment by djc** [comment]
> It is strange if Der::Owned is not equal to Der::Borrowed for the same key when we compare Vec<u8>.into() vs &[u8].into().

That definitely sounds wrong, please send a PR for that.
